package com.mif.interview.yapily.model;

public enum PaymentUserGroup {
  WHOLESALE_FI_FI,
  COMMERCIAL,
  CONSUMER_GOODS_SERVICES,
  FINANCE,
  INSURANCE,
  PROPERTY,
  UTILITIES,
  TAX,
  SALARIES_INCOMES,
  INVESTMENTS,
  FOREIGN_EXCHANGE,
  GOVERNMENT,
  BENEFIT_PAYMENTS,
  MEDICAL,
  PENSIONS
}
